Features/settings#75
Mathmeh/EasyInvest pull request #3
Opened 2024-07-22 07:04 UTC by Mathmeh

* Добавлены три экрана и навигация между ними
* добавлен линтер
* добавлена возможность сохранять в настройках дефолтную валюту
* добавлено немного DI
* добавлен bottom sheet

![Безымянныйfd](https://github.com/user-attachments/assets/28755631-8c4f-46ff-a791-54f7d21e47a9
![Безымянный](https://github.com/user-attachments/assets/16425bb9-83f5-4fb3-a1a7-40b8fa99af39)
)

2024-07-22 15:22 UTC, Valentin2508247 requested changes

2024-07-22 15:22 UTC, Valentin2508247 commented on gradle/libs.versions.toml
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

2024-07-22 15:22 UTC, Valentin2508247 commented on app/build.gradle.kts
> +apply(plugin = "com.google.dagger.hilt.android")
в блок plugins через alias(libs.plugins.hilt)

2024-07-22 15:22 UTC, Valentin2508247 commented on app/src/main/java/com/example/easyinvest/DataAcces/SettingsRepositoryImpl.kt
> +class SettingsRepositoryImpl(context: Context) : SettingsRepository {
@ Inject constructor

2024-07-22 15:22 UTC, Valentin2508247 commented on app/src/main/java/com/example/easyinvest/DataAcces/SettingsRepositoryImpl.kt
> +    private val _currrencyPrefName =
в ресурсы нужно выносить строки, показываемые юзеру на экране
сделайте const val DEFAULT_CURRENCY_KEY в companion object

2024-07-22 15:22 UTC, Valentin2508247 commented on app/src/main/java/com/example/easyinvest/Domain/Entity/Currency.kt
> +        public fun getCurrIndex(day: String): Int {
почему нейминг day?

2024-07-22 15:22 UTC, Valentin2508247 commented on app/src/main/java/com/example/easyinvest/presentation/settings/FragmentSettings.kt
> +    private lateinit var fragmentSettingsViewModel: FragmentSettingsViewModel
через делегат by viewModels

2024-07-22 15:22 UTC, Valentin2508247 commented on app/src/main/java/com/example/easyinvest/presentation/settings/FragmentSettings.kt
> +        fragmentSettingsViewModel.getCurrencySettings
перенести в onViewCreated

2024-07-22 15:22 UTC, Valentin2508247 commented on app/src/main/java/com/example/easyinvest/presentation/settings/BottomSheet/CurrencyBottomSheet.kt
> +    private lateinit var settingsViewModel: FragmentSettingsViewModel
через делегат by viewModels

2024-07-22 15:22 UTC, Valentin2508247 commented on app/src/main/java/com/example/easyinvest/presentation/settings/BottomSheet/CurrencyBottomSheet.kt
> +        return inflater.inflate(R.layout.bottom_sheet_currency, container, false)
почему не через binding?

2024-07-22 15:22 UTC, Valentin2508247 commented on app/src/main/java/com/example/easyinvest/presentation/settings/FragmentSettingsViewModel.kt
> +    private var _getCurrencySettings = MutableLiveData<String>().apply {
private val

2024-07-22 15:22 UTC, Valentin2508247 commented on app/src/main/java/com/example/easyinvest/presentation/settings/FragmentSettingsViewModel.kt
> +@Inject constructor(private val settingsProvider: SettingsRepositoryImpl) : ViewModel() {
тут зависим от реализации, а не абстракции
private val settingsProvider: SettingsRepository

2024-07-22 15:22 UTC, Valentin2508247 commented on app/src/main/java/com/example/easyinvest/presentation/settings/FragmentSettingsViewModel.kt
> +    val getCurrencySettings: LiveData<String> get() = _getCurrencySettings
некорректный нейминг двух лайвдат
сама по себе livedata ничего не получает
нельзя добавлять get в название

2024-07-22 15:22 UTC, Valentin2508247 commented on app/src/main/res/layout/bottom_sheet_currency.xml
можно сразу ListView

2024-07-22 15:22 UTC, Valentin2508247 commented on app/src/main/res/layout/fragment_settings.xml
> +        android:text="USD"
через ресурсы

2024-07-22 15:22 UTC, Valentin2508247 commented on gradle/libs.versions.toml
> +javapoet = "1.13.0"
зачем javapoet?

2024-07-22 15:22 UTC, Valentin2508247 commented on gradle/libs.versions.toml
> +javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }
зачем javapoet?

2024-07-22 15:22 UTC, Valentin2508247 commented on build.gradle.kts
> +    id("com.google.dagger.hilt.android") version "2.51.1" apply false
из versionCatalog

2024-07-25 09:52 UTC, Valentin2508247 requested changes

2024-07-25 09:52 UTC, Valentin2508247 commented on app/src/main/java/com/example/easyinvest/presentation/settings/BottomSheet/CurrencyBottomSheet.kt
> +        val listView: ListView = view.findViewById(R.id.listView)
не нужно

2024-07-25 09:52 UTC, Valentin2508247 commented on app/src/main/java/com/example/easyinvest/presentation/settings/BottomSheet/CurrencyBottomSheet.kt
> +        listView.adapter = adapter
binding.listView.apply {
    adapter = adapter
    ...
}

2024-07-25 09:52 UTC, Valentin2508247 commented on app/src/main/java/com/example/easyinvest/presentation/settings/FragmentSettings.kt
> +            parentFragmentManager, bottomSheet.tag
если не ошибаюсь, тут bottomSheet.tag будет пустым
давай сделаем const val TAG = "TAG_CURRENCY_BOTTOM_SHEET"  в companion object CurrencyBottomSheet
в этом месте parentFragmentManager, CurrencyBottomSheet.TAG

2024-07-25 09:52 UTC, Valentin2508247 commented on app/src/main/res/layout/fragment_settings.xml
> +
лишние пустые строки

2024-07-25 09:52 UTC, Valentin2508247 commented on app/src/main/res/values/strings.xml
> +    <string name="currency_prefs">currency_prefs</string>
ненужная строка

2024-07-25 09:52 UTC, Valentin2508247 commented on app/build.gradle.kts
> +apply(plugin = "com.google.dagger.hilt.android")
2 раза плагин объявлен
удали apply(plugin = "com.google.dagger.hilt.android")

2024-07-25 10:17 UTC, Valentin2508247 approved these changes

2024-07-25 12:12 UTC, denverden approved these changes

2024-07-25 15:22 UTC, merged