Features/portfoliolist#87
Mathmeh/EasyInvest pull request #5
Opened 2024-08-01 06:49 UTC by denverden

Предварительный список портфеля. Минимальная реализация.

![Screenshot_portfolio](https://github.com/user-attachments/assets/a156e6ce-352a-432a-a9d2-6a0535abb60c)

2024-08-01 14:22 UTC, Valentin2508247 requested changes

2024-08-01 14:22 UTC, Valentin2508247 commented on app/src/main/java/com/example/easyinvest/Domain/Entity/Portfolio.kt
> +open class Portfolio(
не вижу наследников
сделай просто data class, equals / hashcode сами сгенерируются

2024-08-01 14:22 UTC, Valentin2508247 commented on app/src/main/java/com/example/easyinvest/presentation/portfolio/FragmentPortfolioViewModel.kt
> +        value = portfolioProvider.getListPortfolio()
обращение к репозиторию через функцию
и вызвать функцию из фрагмента
лучше не писать вызовы методов в ините, легче будет тестировать

2024-08-01 14:22 UTC, Valentin2508247 commented on app/src/main/java/com/example/easyinvest/presentation/portfolio/rv/PortfolioAdapter.kt
> +
?

2024-08-01 14:22 UTC, Valentin2508247 commented on app/src/main/java/com/example/easyinvest/presentation/portfolio/rv/PortfolioViewHolder.kt
> +
?

2024-08-02 07:02 UTC, denverden commented on app/src/main/java/com/example/easyinvest/Domain/Entity/Portfolio.kt
> +open class Portfolio(
исправил

2024-08-02 07:03 UTC, denverden commented on app/src/main/java/com/example/easyinvest/presentation/portfolio/FragmentPortfolioViewModel.kt
> +        value = portfolioProvider.getListPortfolio()
исправил

2024-08-02 07:12 UTC, denverden commented on app/src/main/java/com/example/easyinvest/presentation/portfolio/rv/PortfolioAdapter.kt
> +
тут не понятно, что за вопрос?

2024-08-02 07:12 UTC, denverden commented on app/src/main/java/com/example/easyinvest/presentation/portfolio/rv/PortfolioViewHolder.kt
> +
тут тоже не понятно, что за вопрос?

2024-08-02 12:12 UTC, Valentin2508247 commented on app/src/main/java/com/example/easyinvest/presentation/portfolio/rv/PortfolioAdapter.kt
> +
пустая строка

2024-08-02 12:12 UTC, Valentin2508247 commented on app/src/main/java/com/example/easyinvest/presentation/portfolio/rv/PortfolioViewHolder.kt
> +
пустая строка

2024-08-02 12:13 UTC, Valentin2508247 approved these changes

2024-08-04 08:58 UTC, Mathmeh approved these changes

2024-08-04 17:58 UTC, merged